language: node_js
compiler: gcc
cache:
  directories:
    - ~/.npm

os:
  - linux
  - osx

notifications:
  email: false

node_js:
  - '12'
  - '10'
  - '8'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libbluetooth-dev

script: echo "Building against $(node -v) ..."

jobs:
  include:
    - stage: release
      node_js: '12'
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run build && npx semantic-release
        on:
          branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
